Add apache http client
ClickHouse/clickhouse-jdbc pull request #1146
Opened 2022-12-04 06:58 UTC by JackyWoo

This pr try wo close #1139 .

2022-12-04 13:20 UTC, zhicwu requested changes

2022-12-04 13:20 UTC, zhicwu commented on pom.xml
> +        <apache.httpclient.version>4.5.13</apache.httpclient.version>
The legacy driver was using http client 4.5 and it's known to have "no response" error sometimes. Can we [migrate to 5.2](https://hc.apache.org/httpcomponents-client-5.2.x/migration-guide/preparation.html)?

2022-12-04 13:20 UTC, zhicwu commented on clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java
> +import com.clickhouse.client.config.ClickHouseOption;
Remove unnecessary changes.

2022-12-04 13:20 UTC, zhicwu commented on clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseSocketOption.java
> +    IP_TOS("socket_op_ip_tos", 0, "Socket IP_TOS option which indicates IP package priority.");
Why not simply add this into `ClickHouseClientOption`?

2022-12-04 13:26 UTC, zhicwu commented
Thank you @JackyWoo for the pull request. Just added a few immediate feedback. Apart from that, we also need to update pom to ensure Apache libraries will be only included in -all jar. Will run benchmark tomorrow to understand more.

2022-12-05 06:32 UTC, zhicwu commented
The performance does not look good somehow.

```
Benchmark                                     (client)  (connection)  (statement)   (type)   Mode  Cnt    Score   Error  Units
Query.selectInt8    clickhouse-apache-http-client-jdbc         reuse     prepared  default  thrpt   20   95.181 ± 3.783  ops/s
Query.selectInt8                  clickhouse-http-jdbc         reuse     prepared  default  thrpt   20  112.334 ± 7.949  ops/s
Query.selectString  clickhouse-apache-http-client-jdbc         reuse     prepared  default  thrpt   20   27.539 ± 0.925  ops/s
Query.selectString                clickhouse-http-jdbc         reuse     prepared  default  thrpt   20   35.449 ± 2.106  ops/s
Query.selectUInt64  clickhouse-apache-http-client-jdbc         reuse     prepared  default  thrpt   20   45.539 ± 1.620  ops/s
Query.selectUInt64                clickhouse-http-jdbc         reuse     prepared  default  thrpt   20   62.749 ± 4.282  ops/s
```

2022-12-05 07:02 UTC, JackyWoo commented
May I ask how to configure `client`?

2022-12-05 08:10 UTC, zhicwu commented
> May I ask how to configure benchmark `client` to `clickhouse-apache-http-client-jdbc`?

Please pull latest code fron your branch and follow instructions below.

```bash
cd clickhouse-benchmark
mvn -Drelease clean package
java -jar target/benchmarks.jar -p client=clickhouse-apache-http-client-jdbc -p type=default -p connection=reuse Query.selectInt8
```

2022-12-05 12:46 UTC, JackyWoo commented
Optimize apache http client by reuse connection. Below is benchmark in my local machine.

````
Benchmark               (client)  (connection)  (statement)   (type)   Mode  Cnt    Score   Error  Units
Query.selectInt8  ClickhouseJdbc         reuse     prepared  default  thrpt   20   96.870 ± 5.932  ops/s
Query.selectInt8  ClickhouseJdbc         reuse     prepared   string  thrpt   20   96.102 ± 7.897  ops/s
Query.selectInt8  ClickhouseJdbc         reuse     prepared   object  thrpt   20  100.323 ± 8.398  ops/s

Benchmark                               (client)  (connection)  (statement)   (type)   Mode  Cnt    Score   Error  Units
Query.selectInt8  ClickhouseApacheHttpClientJdbc         reuse     prepared  default  thrpt   20  107.038 ± 4.379  ops/s
Query.selectInt8  ClickhouseApacheHttpClientJdbc         reuse     prepared   string  thrpt   20  107.169 ± 3.687  ops/s
Query.selectInt8  ClickhouseApacheHttpClientJdbc         reuse     prepared   object  thrpt   20  109.726 ± 2.098  ops/s

```

2022-12-07 16:17 UTC, JackyWoo commented
@zhicwu Please review the PR, when you have a changce.

2022-12-08 00:31 UTC, zhicwu commented
Thank you for the contribution @JackyWoo. I was waiting the build failure got fixed :)

The benchmark makes sense as they should be similar, and the result could be slightly different when using single thread vs. multi-thread for the benchmark.

Anyway, just document my concerns and may change the code after merging this PR.
* Is `ByteArraysInputStream` really needed?
* Consider `CloseableHttpAsyncClient`
* Packing - change httpclient5 to provided?
* Stress test to understand if we still have "no response" error

Lastly, while I'm working on TCP client, if we need better control of Socket, we probably need non-blocking SocketChannel based implementation as well.

2022-12-08 00:32 UTC, zhicwu approved these changes

2022-12-08 00:33 UTC, merged

2022-12-08 08:09 UTC, JackyWoo commented
@zhicwu Thank you,  may I know when 0.33 will release?