Return proper error when user tries to enable transactions
ClickHouse/clickhouse-jdbc pull request #659
Opened 2021-05-10 14:38 UTC by findepi

Transactions are not supported, so `setAutoCommit(false)` should fail,
as it does not provide the isolation or rollback-ability requested by
the caller.

`commit()` and `rollback()` should fail in auto-commit mode (this is
what PostgreSQL JDBC driver does).

2021-05-10 22:01 UTC, zhicwu requested changes

2021-05-10 22:07 UTC, zhicwu commented
Thanks @findepi. We probably need an option to make it acting like a full featured driver, so that it will work with more clients.

2021-05-10 22:08 UTC, zhicwu commented
Thanks @findepi. We probably need an option to make it acting like a full featured driver, so that it will work with more clients.

2021-05-11 07:20 UTC, findepi commented on clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java
> +        throw new SQLException("Cannot commit when auto-commit is enabled");
thanks, changed

2021-05-11 11:04 UTC, merged

2021-05-11 13:28 UTC, findepi commented
thanks for a quick merge!